"""
Build the master catalog and intake events for the REAL (Open Food Facts) run.

  python3 scripts/build_real_pipeline.py

WHAT IS REAL HERE AND WHAT IS NOT -- this matters more than any number below.

  REAL  the master catalog: 2,000+ actual UK grocery products, with the brand
        names, product names, pack sizes and GS1 barcodes they really carry.
  REAL  the packaging photographs: contributor phone photos of the actual packs,
        with glare, angles, curved surfaces and foreign-language panels.
  REAL  the catalog's density and its messiness -- "GREEN & BLACK'S ORGANIC"
        and "Green & Black's" are two separate records for one brand, and
        0.3% of the barcodes fail their own checksum.

  SIMULATED  the supplier submission. Open Food Facts is a product database,
        not a supplier feed; nobody publishes the malformed spreadsheets a
        retailer actually receives. So the submission is generated by corrupting
        the real record, exactly as in the synthetic run.

So the artwork-vs-master leg is a genuine measurement -- a real photograph read
by OCR and compared against a real catalog record. The supplier leg is not, and
no claim resting on it should be presented as real-world evidence.
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import paths  # noqa: E402
from corrupt_supplier_feed import corrupt_row  # noqa: E402
from normalize import normalize_quantity, normalize_text  # noqa: E402
from stage06_barcode_verify import is_valid_gtin  # noqa: E402

SEED = 4242

SCHEMA = """
CREATE TABLE IF NOT EXISTS master_catalog (
    master_id     INTEGER PRIMARY KEY,
    gtin          TEXT,
    brand         TEXT NOT NULL,
    product_name  TEXT NOT NULL,
    quantity      TEXT,
    category      TEXT,
    image_url     TEXT
);
"""


def load_raw() -> list[dict]:
    path = paths.run_dir("real") / "catalog_raw.json"
    if not path.exists():
        raise SystemExit(
            "No fetched catalog. Run:\n"
            "  python3 scripts/fetch_open_food_facts.py --pages 3 --images 140"
        )
    return json.loads(path.read_text())


def build_catalog(records: list[dict]) -> list[tuple]:
    rows = []
    for i, r in enumerate(records, start=1):
        rows.append((i, r["code"], r["brand"] or "(no brand)", r["product_name"],
                     r["quantity"], r["category"], r["image_url"]))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit-events", type=int, default=None,
                    help="cap intake events (defaults to every product with a photo)")
    args = ap.parse_args()

    run = paths.ensure("real")
    db = paths.db_path("real")
    records = load_raw()

    # --- master catalog -----------------------------------------------------
    catalog = build_catalog(records)
    conn = sqlite3.connect(db)
    conn.executescript(SCHEMA)
    conn.execute("DELETE FROM master_catalog")
    conn.executemany(
        "INSERT INTO master_catalog (master_id, gtin, brand, product_name, "
        "quantity, category, image_url) VALUES (?,?,?,?,?,?,?)", catalog)
    conn.commit()
    conn.close()
    print(f"Master catalog: {len(catalog)} real products -> {db}")

    # --- intake events, one per downloaded photograph -----------------------
    img_dir = run / "images"
    by_code = {r["code"]: r for r in records}
    id_by_code = {c[1]: c[0] for c in catalog}

    photos = sorted(img_dir.glob("front_*.jpg")) if img_dir.exists() else []
    if args.limit_events:
        photos = photos[: args.limit_events]
    if not photos:
        raise SystemExit(
            "No packaging photos downloaded yet. Run:\n"
            "  python3 scripts/fetch_open_food_facts.py --pages 3 --images 140"
        )

    # OCR output, if stage 01 has already run over the photographs. The barcode
    # is never among it: Open Food Facts' UK slice carries only front-of-pack
    # views, and the barcode is printed on the back. That is not a gap in the
    # reading -- it reflects how intake actually works, where the barcode comes
    # off a scanner at goods-in rather than out of a photograph.
    ocr_by_id: dict[int, dict] = {}
    ocr_path = run / "artwork_extracted.csv"
    if ocr_path.exists():
        for r in csv.DictReader(open(ocr_path, newline="")):
            ocr_by_id[int(r["master_id"])] = r

    events = []
    for img in photos:
        code = img.stem.replace("front_", "")
        rec = by_code.get(code)
        if rec is None or code not in id_by_code:
            continue
        master_id = id_by_code[code]

        # The supplier submission is SIMULATED -- see the module docstring.
        random.seed(SEED + master_id)
        row = (master_id, rec["code"], rec["brand"] or "(no brand)",
               rec["product_name"], rec["quantity"], rec["category"])
        sup = corrupt_row(row)

        events.append({
            "event_id": f"real_{master_id}",
            "true_master_id": master_id,
            "image_path": str(img.relative_to(paths.ROOT)),

            # artwork_* from ocr_extract --mode real. There is no structured
            # brand/name/quantity on a photograph, so the whole OCR blob goes
            # into the text field and the matcher is given all of it.
            "artwork_brand": "",
            "artwork_product_name": (ocr_by_id.get(master_id, {})
                                     .get("extracted_brand", ""))[:400],
            "artwork_quantity": "",
            "artwork_gtin": ocr_by_id.get(master_id, {}).get("extracted_gtin", ""),
            "artwork_norm_brand": "",
            "artwork_norm_quantity": "",

            "supplier_raw_brand": sup["submitted_brand"],
            "supplier_raw_product_name": sup["submitted_product_name"],
            "supplier_raw_quantity": sup["submitted_quantity"],
            "supplier_raw_gtin": sup["submitted_gtin"],
            "supplier_norm_brand": normalize_text(sup["submitted_brand"]),
            "supplier_norm_product_name": normalize_text(sup["submitted_product_name"]),
            "supplier_norm_quantity": normalize_quantity(sup["submitted_quantity"]),
            "supplier_norm_gtin": re.sub(r"\D", "", sup["submitted_gtin"]),
            "supplier_corruption_applied": sup["corruption_applied"],

            "master_brand": rec["brand"] or "(no brand)",
            "master_product_name": rec["product_name"],
            "master_quantity": rec["quantity"],
            "master_gtin": rec["code"],
            "master_norm_brand": normalize_text(rec["brand"] or ""),
            "master_norm_quantity": normalize_quantity(rec["quantity"] or ""),
        })

    out = run / "intake_events.csv"
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(events[0].keys()))
        w.writeheader()
        w.writerows(events)
    print(f"Intake events: {len(events)} (one per real photograph) -> {out}")

    valid = sum(is_valid_gtin(e["master_gtin"]) for e in events)
    print(f"  events whose catalog barcode is a parseable GS1 code: "
          f"{valid}/{len(events)} ({valid/len(events):.1%})")
    print("\nNext: python3 scripts/ocr_extract.py --mode real")


if __name__ == "__main__":
    main()
